---
- hosts: vm
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.https_proxy}}"
    no_proxy: "{{proxy.no_proxy}}"

  pre_tasks:
    - name: install packages
      become: true
      ansible.builtin.package:
        name:
          - git
        state: present

  roles:
    
    - { role: apt, tags: apt}
    - { role: docker, tags: docker}
    - { role: kubectl, tags: kubectl}
    - { role: kpt, tags: kpt}
    - { role: bash, tags: bash }
    - { role: tree, tags: tree}
    - { role: nephio/install, tags: nephio}
    - { role: clab, tags: clab}
