## © 2023 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: ensure repository key is installed
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker registry is available
  become: true
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

- name: ensure docker and dependencies are installed
  become: true
  apt: name=docker-ce update_cache=yes

- name: Remove file (delete file) config.toml
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restart service containerd, in all cases
  ansible.builtin.service:
    name: containerd
    state: restarted
