## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0
---
- name: Copy cluster config template
  template:
    src: "{{ role_path }}/templates/cluster-config.yaml.j2"
    dest: "{{ tmp_directory }}/{{ item.key }}-cluster-config.yaml"
    mode: 0644
  tags:
    - create

- name: Add extra port mapping for mgmt cluster ingress
  shell: |
    cat <<EOF >> {{ tmp_directory }}/{{ item.key }}-cluster-config.yaml
        kubeadmConfigPatches:
        - |
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: "ingress-ready=true"
        extraPortMappings:
        - containerPort: 80
          hostPort: 7007
          protocol: TCP
    EOF
  when: item.key == "mgmt"

- name: Start_K8s
  shell: kubeadm init --pod-network-cidr={{ item.value.pod_subnet }} --service-cidr={{ item.value.svc_subnet }} >> cluster_initialized.txt
  become: yes
  become_user: root
  args:
    chdir: $HOME
    creates: /root/cluster_initialized.txt
  when: item.key == "mgmt"
